### ISSUE TITLE
merge 문제

### ISSUE THREAD

**Issue by ParkJiYeong-Hufs** [ParkJiYeoung8297/Phython_in_Hufs_class#5]
추가하신 commit을 merge 안하고 코드를 수정했더니 merge 가 안됩니다 (계속 pull request하라고 뜸)

**Comment by ParkJiYeoung8297** [comment]
코드 수정한 부분을 다른곳에 복사해두시고 그 이전 상태로 다시 수정하시면 merge가 될거에요
merge 후에 수정한 부분 코드 다시 추가해주세요
(아마 수정하신 부분 pull request 안한 상태에서 제 commit이 남아서 기존 파일과 달라져서 conflict한것 같습니다)
